[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
body = """
{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{{ commit.message | upper_first }}
    {%- endfor %}
{% endfor %}\n
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat",     group = "Features" },
    { message = "^fix",      group = "Bug fixes" },
    { message = "^perf",     group = "Performance" },
    { message = "^refactor", group = "Refactor" },
    { message = "^docs?",    group = "Documentation" },
    { message = "^test",     group = "Testing" },
    { message = "^build",    group = "Build" },
    { message = "^ci",       group = "CI/CD" },
    { message = "^chore",    group = "Miscellaneous" },
    { message = "^revert",   group = "Reverts" },
]
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "newest"

[bump]
features_always_bump_minor = true
breaking_always_bump_major = true
