name: Bug Report
labels: ["type: bug"]
description: Create a report to help us improve

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a complete bug report.
        Before submitting your issue, please review [the contribution guidelines](https://github.com/pivoshenko/poetry-plugin-dotenv/blob/main/CONTRIBUTING.md).
        Feel free to use markdown syntax in text areas.

  - type: textarea
    attributes:
      label: Description
      description: |
        Please describe what happened, with as much pertinent information as you can.
        If applicable, add screenshots to help explain your problem.
        Also, ensure that the feature is not already done in the [latest](https://github.com/pivoshenko/poetry-plugin-release/releases/latest) release.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Workarounds
      description: |
        Is there a mitigation or workaround that allows users to avoid the issue today?
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System
      description: |
        What Operating System are you using?
      placeholder: "Fedora 39"
    validations:
      required: true

  - type: input
    attributes:
      label: poetry version
      description: |
        Please attach output from `poetry --version`
    validations:
      required: true

  - type: input
    attributes:
      label: poetry-plugin-dotenv version
      description: |
        Please attach output from `poetry self show poetry-plugin-dotenv`
    validations:
      required: true

  - type: textarea
    attributes:
      label: Example pyproject.toml
      description: |
        Please provide an example `pyproject.toml` demonstrating the issue.
      render: TOML
    validations:
      required: false

  - type: textarea
    attributes:
      label: Runtime logs
      description: |
        Please attach logs from the failing command using `poetry -vvv <command>`
      render: bash session
    validations:
      required: true
