name: Feature Request
labels: ["type: enhancement"]
description: Suggest an idea for this project

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a complete feature request report.
        Before submitting your issue, please review [the contribution guidelines](https://github.com/pivoshenko/poetry-plugin-dotenv/blob/main/CONTRIBUTING.md).
        If the issue is trivial, why not submit a pull request instead?
        Feel free to use markdown syntax in text areas.

  - type: dropdown
    attributes:
      label: Feature kind
      description: |
        What best describes this feature?
      options:
        - Brand new capability
        - Change in the current behaviour
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe it
      description: |
        A clear and concise description of what the problem is.
        If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the feature
      description: |
        Please describe the proposed feature, with as much pertinent information as you can.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Impact
      description: |
        Please describe the motivation for this feature. Describe, as best you can, how this improves or impacts the users and why this is important.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Workarounds
      description: |
        Is there a mitigation, workaround, or addon that allows users to achieve the same functionality today?
    validations:
      required: false
