name: Feature Request
labels: ["type: enhancement"]
description: Suggest an idea for this project

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a complete feature request.
        Before submitting your issue, please review [the contribution guidelines](https://github.com/pivoshenko/poetry-plugin-dotenv/blob/main/CONTRIBUTING.md).
        If the issue is trivial, consider submitting a pull request instead.
        Feel free to use Markdown syntax in text areas.

  - type: dropdown
    attributes:
      label: Feature Kind
      description: |
        What best describes this feature?
      options:
        - Brand new capability
        - Change in the current behavior
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe it.
      description: |
        A clear and concise description of what the problem is.
        If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the Feature
      description: |
        Please describe the proposed feature, with as much pertinent information as possible.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Impact
      description: |
        Please describe the motivation for this feature. Explain, as best you can, how it improves or impacts users and why it is important.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Workarounds
      description: |
        Is there a mitigation, workaround, or addon that allows users to achieve the same functionality today?
    validations:
      required: false
