name: Feature Request
labels: ["type: enhancement"]
description: Suggest an idea for this project

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a complete feature request.
        Before submitting your issue, please review [the contribution guidelines](https://github.com/pivoshenko/poetry-plugin-dotenv/blob/main/CONTRIBUTING.md).
        For trivial improvements, please consider submitting a pull request instead.
        Feel free to use Markdown syntax in all text areas.

  - type: dropdown
    attributes:
      label: Feature Type
      description: |
        What best describes this feature request?
      options:
        - Brand new capability
        - Change to current behaviour
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem Statement
      description: |
        Is your feature request related to a problem? Please provide a clear and concise description.
        Include screenshots if they help explain the issue.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Proposed Feature
      description: |
        Please describe the desired feature with as much pertinent information as possible.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Impact and Motivation
      description: |
        Please explain the motivation for this feature. How would it improve or impact users, and why is it important?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Workarounds
      description: |
        Are there any existing workarounds or addons that allow users to achieve similar functionality today?
    validations:
      required: false
