
[tool.poetry.plugins.dotenv]
ignore = "true"
location = ".env.dev"

[tool.poetry]
name = "poetry-plugin-dotenv"
version = "0.0.1"
description = "..."
license = "MIT"
authors = ["Volodymyr Pivoshenko <volodymyr.pivoshenko@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
