# Requires GitHub secrets
# - GH_TOKEN

name: Labels

on:
  push:
    branches: ["main"]
    paths:
      - ".github/labels.yaml"
      - ".github/workflows/labels.yaml"
  workflow_dispatch:

concurrency:
  group: labels-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          yaml-file: .github/labels.yaml
