# Requires GitHub secrets
# - GH_TOKEN

name: Stale PRs
on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  stale:
    permissions:
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: "This pull request is stale because it has been open for thirty days with no activity. Please update PR and respond to this comment if you're still interested in working on this."
          stale-pr-label: "stale"
          days-before-pr-stale: 30
          days-before-close: -1
          remove-stale-when-updated: false
          debug-only: false
